
import { Module, ModuleType, GrammatikPunkt } from './types';
import BookIcon from './components/icons/BookIcon';
import HeadphonesIcon from './components/icons/HeadphonesIcon';
import PuzzleIcon from './components/icons/PuzzleIcon';
import PencilIcon from './components/icons/PencilIcon';
import MicIcon from './components/icons/MicIcon';
import GrammarIcon from './components/icons/GrammarIcon';

export const MODULES: Module[] = [
  {
    id: ModuleType.Leseverstehen,
    title: 'Leseverstehen',
    icon: BookIcon,
    color: 'blue',
    description: 'La compréhension de la lecture a trois parties qui sont: Leseverstehen Teil 1, Leseverstehen Teil 2 et Leseverstehen Teil 3.',
    instructions: 'Vous êtes ici sur les parties "explication"et "examen".'
  },
  {
    id: ModuleType.Hoerverstehen,
    title: 'Hörverstehen',
    icon: HeadphonesIcon,
    color: 'green',
    description: 'Compréhension orale. Écoutez des audios et démontrez votre compréhension.',
    instructions: 'Vous entendrez des conversations et des annonces, puis répondrez à des questions de type "Vrai/Faux" et "Choix multiples".'
  },
  {
    id: ModuleType.Sprachbausteine,
    title: 'Sprachbausteine',
    icon: PuzzleIcon,
    color: 'purple',
    description: 'Éléments linguistiques. Montrez votre maîtrise de la grammaire et du vocabulaire.',
    instructions: 'Cette partie contient 10 questions de grammaire à choix multiples et un texte à trous pour le vocabulaire.'
  },
  {
    id: ModuleType.SchriftlicherAusdruck,
    title: 'Schriftlicher Ausdruck',
    icon: PencilIcon,
    color: 'orange',
    description: 'Expression écrite. Rédigez un texte formel ou informel sur un sujet donné.',
    instructions: 'Vous recevrez un sujet et 4 points directeurs pour rédiger un e-mail ou une lettre.'
  },
  {
    id: ModuleType.MuendlicherAusdruck,
    title: 'Mündlicher Ausdruck',
    icon: MicIcon,
    color: 'red',
    description: 'Expression orale. Simulez les différentes parties de l\'examen oral.',
    instructions: 'Préparez-vous à vous présenter, à parler d\'un sujet et à planifier quelque chose avec un partenaire.'
  },
  {
    id: ModuleType.Grammatik,
    title: 'Grammatik A2',
    icon: GrammarIcon,
    color: 'yellow',
    description: 'Selbsttest A2 – Grammaire et compréhension grammaticale. Révisez les bases avant d\'attaquer le B1.',
    instructions: 'Choisissez un point grammatical, entraînez-vous avec des exercices interactifs et obtenez des explications claires.'
  }
];

export const GRAMMATIK_PUNKTE: GrammatikPunkt[] = [
    // Fix: Added the missing 'explanation' property to each object.
    { id: 1, title: 'Haupt- und Nebensätze', objective: 'Verstehen, wann das Verb am Ende steht.', explanation: 'In Nebensätzen, die mit Konjunktionen wie \'weil\', \'dass\' oder \'wenn\' beginnen, steht das konjugierte Verb am Ende des Satzes.', promptDetails: 'Générer un exercice de type QCM (a/b) où il faut choisir la proposition subordonnée correcte, basé sur l\'exemple de l\'image. L\'exercice doit tester la position du verbe à la fin de la phrase dans les subordonnées introduites par "weil", "dass", et "wenn". Fournir 10 questions. Chaque question doit présenter une phrase principale suivie du début d\'une subordonnée, avec deux options pour la fin de la phrase. Exemple : "Hanna ist glücklich, weil a) sie heute Geburtstag hat. b) sie hat heute Geburtstag." Le feedback doit expliquer que dans une proposition subordonnée (Nebensatz), le verbe conjugué se place toujours à la fin.' },
    { id: 2, title: 'Nebensätze mit "weil"', objective: 'Sätze mit "weil" bilden.', explanation: '\'weil\' leitet einen kausalen Nebensatz ein. Das konjugierte Verb steht am Ende des Satzes.', promptDetails: 'Générer un exercice de type "Reformulation" où l\'utilisateur doit combiner deux phrases en une seule à l\'aide de "weil", comme dans l\'exemple "Büroarbeit" de l\'image. Fournir 10 paires de phrases. La première phrase est la proposition principale, la seconde doit être transformée en proposition subordonnée. Exemple : "Input: Der Drucker funktioniert nicht. Das Kabel ist kaputt. -> Output attendu: Der Drucker funktioniert nicht, weil das Kabel kaputt ist.". L\'utilisateur doit écrire la phrase complète. Le feedback doit expliquer que "weil" introduit une cause et que le verbe conjugué de la subordonnée doit être placé à la fin.' },
    { id: 3, title: 'Nebensätze mit "wenn"', objective: 'Bedingung oder Gewohnheit ausdrücken.', explanation: '\'wenn\' leitet einen konditionalen oder temporalen Nebensatz ein. Steht der Nebensatz am Anfang, beginnt der Hauptsatz mit dem Verb.', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) basé sur les exemples de l\'image. L\'exercice doit tester la construction de phrases avec "wenn". Fournir 10 questions. Chaque question présente une phrase ou une paire de phrases avec un trou à compléter, forçant l\'utilisateur à construire soit la proposition principale, soit la subordonnée avec "wenn". Exemples de format : 1) "Miriam macht Urlaub. -> Wenn Miriam Urlaub macht, ___ sie am liebsten ans Mittelmeer." 2) "Sie sucht im Internet. Wenn sie ein schönes Hotel finden will, ___." L\'utilisateur doit écrire la partie manquante. Le feedback doit expliquer la structure de la phrase : si la subordonnée est en première position, le verbe de la principale vient juste après la virgule (ex: "Wenn..., V2..."). Si la principale est en premier, la subordonnée suit avec le verbe à la fin (ex: "..., wenn ... Vfin.").' },
    { id: 4, title: 'weil, deshalb oder denn', objective: 'Kausalität richtig ausdrücken.', explanation: '\'weil\' (Verb am Ende) und \'denn\' (Verb an Pos. 2) leiten eine Begründung ein. \'deshalb\' (Verb an Pos. 2) leitet eine Folge ein.', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) basé sur l\'exemple "Stadtbesichtigung" de l\'image. L\'utilisateur doit compléter 10 phrases avec le connecteur correct parmi "weil", "deshalb", ou "denn". La consigne doit inclure "Achten Sie auf die Wortstellung." Le feedback doit expliquer la différence de structure : \'weil\' introduit une subordonnée avec le verbe à la fin (ex: ..., weil das Wetter gut war.), \'deshalb\' introduit une conséquence avec le verbe en position 2 (ex: ..., deshalb sind wir spazieren gegangen.), et \'denn\' introduit une cause comme une proposition principale (ex: ..., denn das Wetter war gut.).' },
    { id: 5, title: 'weil oder deshalb – Einkäufe', objective: 'Cause vs conséquence unterscheiden.', explanation: '\'weil\' leitet einen Nebensatz mit einer Begründung ein (Verb am Ende). \'deshalb\' leitet einen Hauptsatz mit einer Folge ein (Verb an Position 2).', promptDetails: 'Générer un exercice de type "Reformulation" basé sur l\'exemple "Einkäufe". Pour chaque question (10 au total), fournir une phrase de départ et deux phrases différentes entre parenthèses. L\'utilisateur doit compléter la phrase de départ de deux manières : une fois en utilisant "weil" avec la première phrase entre parenthèses, et une fois en utilisant "deshalb" avec la seconde. Exemple : "Input: Leandra braucht neue Laufschuhe. (Sie trainiert für einen Marathon.) (Sie geht in ein Sportgeschäft.) -> Output attendu: 1. Leandra braucht neue Laufschuhe, weil sie für einen Marathon trainiert. 2. Leandra braucht neue Laufschuhe, deshalb geht sie in ein Sportgeschäft.". Le feedback doit expliquer la différence de structure : \'weil\' + verbe à la fin vs \'deshalb\' + verbe en position 2.' },
    { id: 6, title: 'weil, dass, wenn, deshalb – Brief', objective: 'Kombinieren und Konnektoren einsetzen.', explanation: 'Konnektoren verbinden Sätze: \'weil\' (Grund, Verb Ende), \'dass\' (Objektsatz, Verb Ende), \'wenn\' (Bedingung, Verb Ende), \'deshalb\' (Folge, Verb Pos. 2).', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) basé sur l\'exemple de l\'image. Le texte doit être une lettre informelle avec 10 trous. L\'utilisateur doit écrire le connecteur correct parmi "weil", "dass", "wenn", et "deshalb" pour chaque trou. Le feedback doit expliquer la fonction du mot correct (ex: "weil" introduit une cause avec le verbe à la fin, "deshalb" introduit une conséquence avec le verbe en position 2, "dass" introduit une complétive, "wenn" une condition).' },
    { id: 7, title: 'W-Fragen (direkt & indirekt)', objective: 'W-Fragen und indirekte Fragen bilden.', explanation: 'In indirekten Fragesätzen (eingeleitet mit einem W-Wort wie \'wer\', \'was\', \'wann\') steht das konjugierte Verb am Ende des Satzes.', promptDetails: 'Générer un exercice en deux parties basé sur l\'exemple de l\'image. Partie A (5 questions) : "Ergänzen Sie das Fragewort." Fournir une phrase réponse. L\'utilisateur doit écrire la question directe correspondante (ex: "Input: Annika hat morgen Geburtstag. -> Output attendu: Wer hat morgen Geburtstag?"). Partie B (5 questions) : "Schreiben Sie jetzt indirekte W-Fragen." Fournir le début d\'une phrase. L\'utilisateur doit la compléter pour former une question indirecte (ex: "Input: Ich weiß nicht, ... -> Output attendu: Ich weiß nicht, wer morgen Geburtstag hat."). Le feedback doit expliquer la formation des questions directes et insister sur la position du verbe à la fin dans les questions indirectes.' },
    { id: 8, title: 'Relativsätze', objective: 'Relativpronomen erkennen und verwenden.', explanation: 'Ein Relativsatz beschreibt ein Nomen aus dem Hauptsatz genauer. Das Relativpronomen (der, die, das, etc.) richtet sich in Genus und Numerus nach dem Bezugswort.', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) où l\'utilisateur doit compléter la phrase avec le pronom relatif correct (der, die, das, den, dem, denen, dessen, deren). Le format doit être une série de 10 phrases sur un thème commun comme "Wohnungssuche" de l\'image (ex: "Ich suche eine Wohnung, ___ im Zentrum liegt."). L\'utilisateur doit écrire le pronom correct. Le feedback doit expliquer le cas, le genre et le nombre du pronom relatif en se référant à son antécédent (ex: "die" est correct car il se réfère à "die Wohnung", qui est féminin singulier et le sujet de la subordonnée).' },
    { id: 9, title: 'Relativsätze – Sätze verbinden', objective: 'Zwei Sätze verbinden.', explanation: 'Zwei Sätze können durch einen Relativsatz verbunden werden. Das Relativpronomen ersetzt ein Nomen oder Pronomen aus dem zweiten Satz.', promptDetails: 'Générer un exercice de type "Reformulation" où l\'utilisateur doit combiner deux phrases en une seule à l\'aide d\'une proposition relative, comme dans l\'exemple de l\'image. Fournir 10 paires de phrases. Exemple de consigne : "Input: Das ist ein tolles Buch. Ich habe es schon dreimal gelesen. -> Output attendu: Das ist ein tolles Buch, das ich schon dreimal gelesen habe.". L\'utilisateur doit écrire la phrase complète. Le feedback doit expliquer quel pronom relatif a été utilisé et pourquoi (ex: "Le pronom \'das\' remplace \'es\' et se réfère à \'das Buch\'.")' },
    { id: 10, title: 'Artikelwörter – Pronomen – Indefinita', objective: 'Unbestimmte/Bestimmte Wörter wählen.', explanation: 'Artikelwörter, Pronomen und Indefinita (z.B. alle, etwas, kein, man) ersetzen oder begleiten Nomen und müssen im richtigen Kasus stehen.', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) basé sur l\'exemple "Überraschung" de l\'image. Crée un dialogue avec 10 trous numérotés. Dans les instructions de l\'exercice (qui ne font pas partie du JSON), mentionne qu\'il faut utiliser les mots d\'une liste fournie (ex: alle, alles, den, die, du, ein, etwas, jeden, kein, man, meinem, mir, niemand, was für eines). L\'utilisateur doit écrire le mot correct dans chaque trou. Le feedback doit expliquer la fonction du mot correct dans la phrase (par exemple, "etwas" est utilisé pour une chose indéfinie, "man" comme un pronom impersonnel).' },
    { id: 11, title: 'Adjektivendungen I', objective: 'Adjektivendungen nach Artikeln.', explanation: 'Die Endung des Adjektivs hängt vom Artikel (bestimmt, unbestimmt, ohne), vom Kasus und vom Genus des Nomens ab.', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) où l\'utilisateur doit compléter les terminaisons des adjectifs. Le format doit consister en 10 phrases individuelles sur un thème comme "Rund um die Kleidung", comme dans l\'image. Chaque phrase doit contenir un adjectif avec une terminaison manquante (ex: "Wie findest du den grün__ Rock?"). L\'utilisateur doit écrire la forme adjectivale complète (ex: "grünen"). Le feedback doit expliquer la règle de déclinaison appliquée (cas, genre, type d\'article).' },
    { id: 12, title: 'Adjektivendungen II – Im Kontext', objective: 'Répéter et automatiser la flexion.', explanation: 'Die Adjektivdeklination folgt festen Regeln. Nach bestimmtem Artikel ist die Endung oft \'-e\' oder \'-en\'. Nach unbestimmtem Artikel übernimmt das Adjektiv oft die Endung des bestimmten Artikels.', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) où l\'utilisateur doit compléter les terminaisons des adjectifs dans un dialogue, comme l\'exemple "Ein netter Abend". Crée un dialogue avec 10 trous. L\'adjectif de base est fourni (ex: "(elegant) Lokal"), et l\'utilisateur doit écrire la forme correcte avec la bonne terminaison (ex: "eleganten"). Le feedback doit expliquer la règle de déclinaison de l\'adjectif en fonction de l\'article, du cas et du genre dans le contexte de la phrase.' },
    { id: 13, title: 'Komparativ', objective: 'Vergleichsformen bilden.', explanation: 'Der Komparativ wird mit \'-er\' gebildet (z.B. schnell -> schneller). Einige Adjektive sind unregelmäßig (gut -> besser, gern -> lieber, viel -> mehr).', promptDetails: 'Générer un exercice de type "Texte à trous" (Reformulation) où l\'utilisateur doit écrire la forme comparative correcte de l\'adjectif entre parenthèses. Le format doit suivre l\'exemple de l\'image : une phrase à compléter avec une comparaison introduite par "als". Inclure des comparatifs réguliers (ex: interessant -> interessanter) et irréguliers (ex: gern -> lieber, gut -> besser, viel -> mehr). Le feedback doit expliquer la règle générale (Adjektiv + -er) et lister les formes irrégulières importantes.' },
    { id: 14, title: 'Wechselpräpositionen – Dativ oder Akkusativ', objective: 'Ort vs Richtung unterscheiden.', explanation: 'Wechselpräpositionen (in, an, auf, etc.) verlangen den Dativ bei einer Ortsangabe (Wo?) und den Akkusativ bei einer Richtungsangabe (Wohin?).', promptDetails: "Générer un exercice de type \"Texte à trous\" (Reformulation) dans le contexte d'un dialogue, comme dans l'image. L'utilisateur doit compléter les trous avec la bonne combinaison de préposition et d'article. L'exercice doit tester la différence entre une localisation (Wo? + Dativ) et une direction (Wohin? + Akkusativ). Le feedback doit impérativement expliquer cette règle. Exemple de feedback : \"On utilise l'accusatif pour une direction (Wohin? - 'Ich stelle die Tasche in den Schrank') et le datif pour une localisation (Wo? - 'Die Tasche ist in dem Schrank').\"" },
    { id: 15, title: 'Ergänzen Sie die Präpositionen im Text', objective: 'Feste Präpositionen trainieren.', explanation: 'Viele Verben, Nomen und Adjektive haben eine feste Präposition, die man lernen muss (z.B. \'warten auf\', \'sich freuen über\', \'Angst vor\').', promptDetails: 'Générer un exercice de type QCM (a/b/c) où il faut compléter les prépositions manquantes dans un texte (de préférence une lettre ou un e-mail). L\'exercice doit être basé sur le modèle de l\'image fournie. Par exemple, pour un texte comme "Liebe Inka, vielen Dank ___ deine E-Mail.", l\'option correcte serait "a) für". Il y aura 10 questions à choix multiples. Le feedback doit expliquer la préposition correcte pour chaque trou. Les prépositions à tester incluent une variété de prépositions dativ, akkusativ, et Wechselpräpositionen, comme : für, in, seit, mit, vom, über, bis zur, bei, im, aus.' },
    { id: 16, title: 'Ergänzen Sie die richtige Verbform im Text', objective: 'Zeitformen & Verben im Kontext richtig einsetzen.', explanation: 'Die Verbform hängt von der Zeitform (Präsens, Perfekt, Präteritum), dem Subjekt und dem Kontext (z.B. Modalverben, Konjunktiv) ab.', promptDetails: 'Générer un exercice de type QCM (a/b/c) basé sur le modèle de l\'image fournie. Le texte doit être une lettre ou un e-mail informel avec des trous numérotés. Pour chaque trou, l\'utilisateur doit choisir la forme verbale correcte parmi trois options. L\'exercice doit tester une variété de points grammaticaux : temps (Präsens, Perfekt, Präteritum), verbes modaux (können, müssen, wollen), auxiliaires (sein, haben), et le Konjunktiv II (wäre, hätte, könnte). Par exemple, pour "eigentlich ___1___ ich mich schon lange bei dir melden", les options pourraient être "a) konnte, b) musste, c) wollte". Il y aura 10 questions. Le feedback doit expliquer pourquoi la forme verbale choisie est correcte en fonction du temps et du contexte.' },
];
